import { Bytes } from "../../dependencies/bytes";
import { MAX_DATAGRAM_SIZE } from "../../dependencies/constants";
import { Struct } from "../../dependencies/struct";
import { Frame } from "../frame";
import { CryptoFlags, CryptoId } from "../ids";
import { VarId } from "../varid";



export const enum TransferParameterFlags {
  WaitBase = 1 << 4,
  MaxDatagramLength = 1 << 5,
  MaxContentLength = 1 << 6,
  HasKey = 1 << 7
}

/** A struct used to send the contents necessary on the handshake */
export class TransferParameter extends Struct {
  static override deserialize<T extends Struct, C extends abstract new (...args: any[]) => T>(this: C, bytes: Bytes): InstanceType<C> {
    const flags = bytes.read_u8();
    let key: Uint8Array | undefined;
    if (flags & TransferParameterFlags.HasKey) key = bytes.slice_from_current_with_length(33).raw();
    let max_content: number | undefined;
    if (flags & TransferParameterFlags.MaxContentLength) max_content = bytes.read_u16();
    let max_datagram_size = MAX_DATAGRAM_SIZE; //default
    if (flags & TransferParameterFlags.MaxDatagramLength) max_datagram_size = bytes.read_u32();
    let wait_base = 2;
    if (flags & TransferParameterFlags.WaitBase) wait_base = bytes.read_u8();
    return new (this as any)(key, max_content, max_datagram_size, wait_base)
  }
  /** Create a new TransferParameters struct used to establish a handshake between 2 ends.
    The provided `key` is the public key generated by ECDH curve25519 that will be used by the other end to retrieve the shared key.
    The provided `max_content` determines how many contents can be sent from one end before receiving a Busy frame.
    The provided `max_datagram_size`, if not provided, defaults to 8kb, is the max amount of size in bytes a datagram can have
    The provided `wait_base`, if not provided, defaults to 2, is the base used to make the end wait `Ticks * WaitBase` ticks after receiving a busy frame to then try sending more data
  */
  constructor(public readonly key?: Uint8Array, public readonly max_content?: number, public readonly max_datagram_size: number = MAX_DATAGRAM_SIZE, public readonly wait_base: number = 2) {
    super();
  }
  override serialize(bytes: Bytes): void {
    const cursor = bytes.advance_cursor(1);
    let flags = 0;
    if (this.key) {
      flags |= TransferParameterFlags.HasKey;
      bytes.write_slice(this.key);
    }
    
    if (this.max_content !== undefined) {
      flags |= TransferParameterFlags.MaxContentLength;
      bytes.write_u16(this.max_content);
    }
    if(this.max_datagram_size !== MAX_DATAGRAM_SIZE) {
      flags |= TransferParameterFlags.MaxDatagramLength;
      bytes.write_u32(this.max_datagram_size);
    }
    if(this.wait_base !== 2) {
      flags |= TransferParameterFlags.WaitBase;
      bytes.write_u8(this.wait_base);
    }
    bytes.write_u8_at(flags, cursor);
  }
  /** Returns the length of this parameter in bytes */
  len(){
    return (this.key?.byteLength ?? 0) +
          (this.max_content !== undefined ? 2 : 0) +
          (this.max_datagram_size !== MAX_DATAGRAM_SIZE ? 4 : 0) +
          (this.wait_base != 2 ? 1 : 0) + 1
  }
}


/** A frame used tp send specifically encrypted data, or atleast, related with it.*/
export class Crypto extends Frame {
  static index = 0;
  /** Creates a new Crypto frame for sending TransportParameters. It's content will be the provided `parameters` serialized */
  static transport(parameters: TransferParameter) {
    const data = Bytes.new(parameters.len());
    parameters.serialize(data);
    data.reset_cursor();
    return new Crypto(CryptoFlags.TransferParameters | CryptoFlags.Fin, data)
  }
  constructor(flags: CryptoFlags, private data: Bytes, private identifier = new VarId(Crypto.index++)) {
    super(new CryptoId(flags));
  }

  override len(): number {
    return 1 + new VarId(this.data.length()).byte_size() + this.identifier.byte_size() + this.data.length();
  }

  override serialize(bytes: Bytes): void {
    bytes.write_u8(+this.id);
    this.identifier.serialize(bytes);
    new VarId(this.data.length()).serialize(bytes);
    bytes.write_slice(this.data.raw());
  }

  ///Retrieves the length of the payload of this crypto frame
  payload_len() {
    return this.data.length();
  }

  /**Returns a new ContentFrame but with data sliced to `amount` */
  sliced(amount: number) {
    return new Crypto(this.id.flags, this.data.slice_to(amount), this.identifier);
  }

  ///Marks this crypto frame as a fin frame
  mark_fin() {
    this.id.flags |= CryptoFlags.Fin;
  }

  /** Unsafe Function. This will retrieve a Transport Parameter from the bytes of this crypto frame. If it's not a transfer parameter, this might break
  the code or get corrupted data*/
  retrieve_transport(){
    return TransferParameter.deserialize(this.data);
  }
}
